"""Embed templates/assets as an importable Python module for pywrangler."""
from pathlib import Path
import pprint

ROOT=Path(__file__).resolve().parents[1]
templates={p.name:p.read_text(encoding='utf-8') for p in sorted((ROOT/'templates').glob('*.html'))}
static={name:((ROOT/'static'/name).read_text(encoding='utf-8'),mime) for name,mime in [('app.css','text/css; charset=utf-8'),('app.js','text/javascript; charset=utf-8'),('store.css','text/css; charset=utf-8'),('store.js','text/javascript; charset=utf-8'),('measurement-guide.svg','image/svg+xml')]}
out='# Generated by scripts/bundle_assets.py; do not edit by hand.\n'
out+='TEMPLATES = '+pprint.pformat(templates,width=120,sort_dicts=True)+'\n'
out+='STATIC = '+pprint.pformat(static,width=120,sort_dicts=True)+'\n'
(ROOT/'bundled_assets.py').write_text(out,encoding='utf-8')
print(f'Bundled {len(templates)} templates and {len(static)} assets.')
